# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'My Corne-ish Zen'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["corneish_zen_v2_left","corneish_zen_v2_right"]'
      alphas: '["colemak"]'
      nav: '["invertedt"]'
      clipboard: '["mac"]'
      branches: '["caksoylar/zmk/caksoylar/zen-v2+mouse"]'
